### ISSUE TITLE
project name

### ISSUE THREAD

**Issue by vborghe** [brainhack-school2020/EliseD_BLUP_Brain-Learning-Unicorn-Project#1]
Hi! I would recommend following the suggested nomenclature for the projects: **(githubname)_(projectname)** So your project would be **Elise-douard_BLUP** 😄 Long live unicorns!

**Comment by Elise-douard** [comment]
Not sure if we can rename the repo?
Do you want me to delete it and create another one with the good name ?

**Comment by vborghe** [comment]
Maybe you can try renaming [https://help.github.com/en/github/administering-a-repository/renaming-a-repository] - not sure it's worth deleting/redoing right now (we can ask tomorrow 😉)

**Comment by Elise-douard** [comment]
It is changed ! thanks Valentina hehe
